# Generated by Django 3.2.7 on 2021-10-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muninnplayer',
            name='points',
        ),
        migrations.AddField(
            model_name='muninnplayer',
            name='daily_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='muninnplayer',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
