# Generated by Django 3.2.7 on 2021-10-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0002_employees_muninnuserv2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userV2',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='MuninnUserv2',
        ),
    ]
