# Generated by Django 3.2.7 on 2021-10-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0002_auto_20211026_1648'),
    ]

    operations = [
    ]
