# Generated by Django 3.2.7 on 2021-10-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0002_auto_20211027_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muninnmasterhabits',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
