# Generated by Django 3.2.7 on 2021-10-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0003_auto_20211026_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuninnDailyHabits',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('master_habit', models.BigIntegerField()),
                ('complete', models.IntegerField()),
            ],
            options={
                'db_table': 'muninn_daily_habits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MuninnMasterHabits',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'muninn_master_habits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MuninnPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('money', models.IntegerField()),
                ('last_day_updates', models.DateField()),
            ],
            options={
                'db_table': 'muninn_player',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
