# Generated by Django 3.2.7 on 2021-10-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muninn', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('file_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
    ]
